[package]
name = "cfctl-cloudflare"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cfctl-auth = { version = "2.0.0-alpha.1", path = "../cfctl-auth" }
cfctl-core = { version = "2.0.0-alpha.1", path = "../cfctl-core" }
async-trait.workspace = true
http.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
chrono.workspace = true

[lints]
workspace = true
